import express from "express";
import authController from "../controllers/authController.js";
import { protect } from "../middleware/verifyToken.js";
import { RateLimiter } from "../middleware/rateLimiter.js";
const router = express.Router();
router.post("/signup", RateLimiter, authController.signup);
router.post("/login", RateLimiter, authController.login);
router.put("/users/:id", authController.updateUser);
router.get("/me", protect, authController.getMe);
router.post("/logout", protect, authController.logout);
export default router;
